{{ config(
    materialized='table',
    schema=env_var('BQ_DATASET_GOLD', env_var('BQ_DATASET', 'nba_gold'))
) }}

with base as (
    select
        season,
        player_id,
        player_name,
        team_abbr,
        opponent_abbr,
        home_away,
        game_date,
        min,
        pts,
        reb,
        ast,
        stl,
        blk,
        tov,
        fantasy_points_simple,
        row_number() over (
            partition by player_id
            order by game_date desc
        ) as game_num,
        max(game_date) over (partition by player_id) as latest_game_date,
        avg(min) over (partition by player_id) as season_avg_min,
        avg(fantasy_points_simple) over (partition by player_id) as season_avg_fantasy_points_simple
    from {{ ref('fct_player_game_stats') }}
),
aggregated as (
    select
        season,
        player_id,
        any_value(player_name) as player_name,
        any_value(team_abbr) as team_abbr,
        max(game_date) as latest_game_date,
        count(*) as season_games,
        round(avg(case when game_num <= 3 then min end), 1) as avg_min_last_3,
        round(avg(case when game_num <= 5 then min end), 1) as avg_min_last_5,
        round(avg(case when game_num <= 10 then min end), 1) as avg_min_last_10,
        round(avg(case when game_num <= 3 then fantasy_points_simple end), 1) as fantasy_points_last_3,
        round(avg(case when game_num <= 5 then fantasy_points_simple end), 1) as fantasy_points_last_5,
        round(avg(case when game_num <= 10 then fantasy_points_simple end), 1) as fantasy_points_last_10,
        round(avg(case when game_num <= 3 then pts end), 1) as pts_last_3,
        round(avg(case when game_num <= 5 then pts end), 1) as pts_last_5,
        round(avg(case when game_num <= 10 then pts end), 1) as pts_last_10,
        round(avg(case when game_num <= 3 then reb end), 1) as reb_last_3,
        round(avg(case when game_num <= 5 then reb end), 1) as reb_last_5,
        round(avg(case when game_num <= 10 then reb end), 1) as reb_last_10,
        round(avg(case when game_num <= 3 then ast end), 1) as ast_last_3,
        round(avg(case when game_num <= 5 then ast end), 1) as ast_last_5,
        round(avg(case when game_num <= 10 then ast end), 1) as ast_last_10,
        round(avg(case when game_num <= 3 then stl end), 1) as stl_last_3,
        round(avg(case when game_num <= 5 then stl end), 1) as stl_last_5,
        round(avg(case when game_num <= 10 then stl end), 1) as stl_last_10,
        round(avg(case when game_num <= 3 then blk end), 1) as blk_last_3,
        round(avg(case when game_num <= 5 then blk end), 1) as blk_last_5,
        round(avg(case when game_num <= 10 then blk end), 1) as blk_last_10,
        round(avg(case when game_num <= 3 then tov end), 1) as tov_last_3,
        round(avg(case when game_num <= 5 then tov end), 1) as tov_last_5,
        round(avg(case when game_num <= 10 then tov end), 1) as tov_last_10,
        round(avg(case when game_num <= 3 then fg3m end), 1) as fg3m_last_3,
        round(avg(case when game_num <= 5 then fg3m end), 1) as fg3m_last_5,
        round(avg(case when game_num <= 10 then fg3m end), 1) as fg3m_last_10,
        round(avg(case when date_diff(latest_game_date, game_date, day) <= 14 then fantasy_points_simple end), 1) as fantasy_points_last_14d,
        round(avg(case when date_diff(latest_game_date, game_date, day) <= 30 then fantasy_points_simple end), 1) as fantasy_points_last_30d,
        round(avg(case when date_diff(latest_game_date, game_date, day) <= 14 then min end), 1) as avg_min_last_14d,
        round(avg(case when date_diff(latest_game_date, game_date, day) <= 30 then min end), 1) as avg_min_last_30d,
        round(max(season_avg_min), 1) as season_avg_min,
        round(max(season_avg_fantasy_points_simple), 1) as season_avg_fantasy_points_simple
    from base
    group by 1, 2
)
select
    season,
    player_id,
    player_name,
    team_abbr,
    latest_game_date,
    season_games,
    avg_min_last_3,
    avg_min_last_5,
    avg_min_last_10,
    avg_min_last_14d,
    avg_min_last_30d,
    fantasy_points_last_3,
    fantasy_points_last_5,
    fantasy_points_last_10,
    fantasy_points_last_14d,
    fantasy_points_last_30d,
    pts_last_3,
    pts_last_5,
    pts_last_10,
    reb_last_3,
    reb_last_5,
    reb_last_10,
    ast_last_3,
    ast_last_5,
    ast_last_10,
    stl_last_3,
    stl_last_5,
    stl_last_10,
    blk_last_3,
    blk_last_5,
    blk_last_10,
    tov_last_3,
    tov_last_5,
    tov_last_10,
    fg3m_last_3,
    fg3m_last_5,
    fg3m_last_10,
    season_avg_min,
    season_avg_fantasy_points_simple,
    round(fantasy_points_last_5 - season_avg_fantasy_points_simple, 1) as fantasy_points_delta_vs_season,
    round(avg_min_last_5 - season_avg_min, 1) as minutes_delta_vs_season
from aggregated
